version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app1:
    build: .
    container_name: ass2-instance-1
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: ass2
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
      SPRING_FLYWAY_LOCATIONS: db/migration

  app2:
    build: .
    container_name: ass2-instance-2
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      SPRING_APPLICATION_NAME: ass2
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_VALIDATE_MIGRATION_NAMING: "true"
      SPRING_FLYWAY_LOCATIONS: db/migration

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
volumes:
  postgres_data:
